DjangoLogin/DjangoLogin/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from .views import *
from rest_framework import  routers
routers=routers.DefaultRouter()
routers.register('goods',GoodsViewsSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/',register),
    path('index/',index),
    path('login/',login),
    path('logout/',logout),
    path('base/',base),
    path('vuedemo/',vuedemo),
    path('goods_list/',goods_list),
    re_path('goods_list/(?P<type>\d{0,1})/(?P<page>\d+)/',goods_list),
    re_path('goods_status/(?P<type>\w+)/(?P<id>\d+)/',goods_status),
    re_path('goods_list_api/(?P<type>\d{0,1})/(?P<page>\d+)/',goods_list_api),
    # path('add_goods/',add_goods),
    path('goodsview/',GoodsView.as_view()),
    re_path('^API',include(routers.urls)),
    path('personal_info/',PersonInfo),

]

DjangoLogin/LoginUser/models.py
from django.db import models

# Create your models here.
GENDER_LIST=(
    (0,'女'),
    (1,'男')
)

class LoginUser(models.Model):
    email=models.EmailField()
    password=models.CharField(max_length=32)
    username = models.CharField(max_length=32)
    phone_number = models.CharField(max_length=32, null=True, blank=True)
    age = models.IntegerField(null=True, blank=True)
    gender = models.IntegerField(null=True, blank=True ,choices=GENDER_LIST)
    photo =models.ImageField(upload_to="img", default="1.jpg")
    address = models.TextField()

    class Meta:
        db_table='loginuser'


class Goods(models.Model):
    goods_number =models.CharField(max_length=32,verbose_name="商品编号")
    goods_name =models.CharField(max_length=32,verbose_name="商品名称")
    goods_price = models.FloatField(verbose_name="商品价格")
    goods_count = models.IntegerField(verbose_name="数量")
    goods_location = models.TextField(verbose_name="生产地")
    goods_safe_data = models.IntegerField(verbose_name="保质期") ##
    goods_pro_time =models.DateField(auto_now=True,verbose_name="生产日期") ##生产日期
    goods_status=models.IntegerField(default=1) ##0下架 1上架
    class Meta:
        db_table = "goods"

DjangoLogin/templates/goods_list.html
{% extends "base.html" %}
{% block title %}
    商品页
{% endblock %}
{% block content %}
    <table class="table">
        <thead>
        <tr>
            <th>商品编号</th>
            <th>商品名称</th>
            <th>商品价格</th>
            <th>商品数量</th>
            <th>商品产地</th>
            <th>商品保质期</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for one in goods_list %}
        <tr>
            <td>{{ one.goods_number }}</td>
            <td>{{ one.goods_name }}</td>
            <td>{{ one.goods_price }}</td>
            <td>{{ one.goods_count }}</td>
            <td>{{ one.goods_location }}</td>
            <td>{{ one.goods_safe_data }}</td>
{#            <td>{{ one.goods_pro_time }}</td>#}
            <td>
                <button class="btn btn-primary">修改</button>
                {% if one.goods_status == 1 %}
                    <a class="btn btn-danger" href="/goods_status/down/{{ one.id }}/">下架</a>
                {% else %}
                    <a class="btn btn-primary" href="/goods_status/up/{{ one.id }}/">上架</a>
                {% endif %}

            </td>
        </tr>
        {% endfor %}
        </tbody>

        <tfoot>
        </tfoot>
    </table>
    <ul style="float: right;margin-right: 50px;" class="pagination">
    {% for page in goods_obj.page_range  %}
        <li class="paginate_button page-item">
            <a class="page-link" href="/goods_list/1/{{ page }}/">{{ page }}</a>
        </li>

    {% endfor %}
    </ul>

{% endblock %}

DjangoLogin/templates/goodslistvue.html
{% extends "base.html" %}
{% block title %}
    商品页
{% endblock %}
{% block style %}
    <script src="/static/js/vue.min.js"></script>
    <script src="/static/js/vue-resource.js"></script>
{% endblock %}
{% block content %}
    {% verbatim %}
    <div id="content">
        <table class="table">
            <thead>
            <tr>
                <th>商品编号</th>
                <th>商品名称</th>
                <th>商品价格</th>
                <th>商品数量</th>
                <th>商品产地</th>
                <th>商品保质期</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>

            <tr v-for="one in goods_list">
                <td>{{ one.goods_number }}</td>
                <td>{{ one.goods_name }}</td>
                <td>{{ one.goods_price }}</td>
                <td>{{ one.goods_count }}</td>
                <td>{{ one.goods_location }}</td>
                <td>{{ one.goods_safe_data }}</td>
                <td>{{ one.goods_pro_time }}</td>

                <td>
                    <button class="btn btn-primary">修改</button>
                    <button class="btn btn-primary">下架</button>

                </td>
            </tr>


            </tbody>
            <tfoot>

            </tfoot>
        </table>
        <ul style="float: right;margin-right: 50px;" class="pagination">


            <li class="paginate_button page-item" v-for="page in page_range">
                <a class='page-link' v-on:click="getpage(page)">{{ page }}</a>
            </li>


        </ul>

    </div>
    {% endverbatim %}
{% endblock %}

{% block script %}
    <script>
        Vue.use(VueResource);  // 指明 下面的vue内容使用的   vueResource
        var vue = new Vue(
            {
                el: "#content",
                data: {
                    goods_list: [
                        {
                            "goods_number": "00001",
                            "goods_name": "白菜",
                            "goods_price": 1000,
                            "goods_count": 100,
                            "goods_location": "北京",
                            "goods_safe_data": 10,
                            "goods_pro_time": "2019-07-01"
                        },
                        {
                            "goods_number": "00001",
                            "goods_name": "白菜",
                            "goods_price": 1000,
                            "goods_count": 100,
                            "goods_location": "北京",
                            "goods_safe_data": 10,
                            "goods_pro_time": "2019-07-01"
                        },
                        {
                            "goods_number": "00001",
                            "goods_name": "白菜",
                            "goods_price": 1000,
                            "goods_count": 100,
                            "goods_location": "北京",
                            "goods_safe_data": 10,
                            "goods_pro_time": "2019-07-01"
                        },
                        {
                            "goods_number": "00001",
                            "goods_name": "白菜",
                            "goods_price": 1000,
                            "goods_count": 100,
                            "goods_location": "北京",
                            "goods_safe_data": 10,
                            "goods_pro_time": "2019-07-01"
                        },
                    ],
                    page_range:[1,2,3,4,5]
                },
                created:function () {
                    // 发送请求
                    url = "/goods_list_api/1/1/",
                    //  相当于  ajax 的发get请求，then 相当于ajax 中的  success
                    this.$http.get(url).then(
                        function (data) {
                            console.log(data.data.data)
                            this.goods_list = data.data.data
                            this.page_range = data.data.page_range
                        },  //   相当于  success
                        function (error) {
                            console.log(error)
                        }, //  相当于  error
                    )
                },
                methods:{
                    "getpage":function (page) {
                        console.log(page)
                        url = "/goods_list_api/1/" + page,
                    //  相当于  ajax 的发get请求，then 相当于ajax 中的  success
                    this.$http.get(url).then(
                        function (data) {
                            console.log(data.data.data)
                            this.goods_list = data.data.data
                            this.page_range = data.data.page_range
                        },  //   相当于  success
                        function (error) {
                            console.log(error)
                        }, //  相当于  error
                    )

                    }
                }
            }
        )


    </script>
{% endblock %}

DjangoLogin/templates/personal_info.html
{% extends "base.html" %}
{% block title %}
    个人中心
{% endblock %}
{% block content %}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table class="table">
            <tr>
                <td rowspan="3" style="width: 300px;">
                    <img style="width:300px;height: 300px;" src="/static/{{ user.photo }}" alt="">
                    <input type="file" name="photo">
                </td>
                <th>邮箱</th>
                <td>
                    <input type="text" name="email" value="{{ user.email }}" disabled>
                </td>
                <th>用户名</th>
                <td>
                    <input type="text" name="username" value="{{ user.username }}">
                </td>
            </tr>
            <tr>
                <th>手机号</th>
                <td>
                    <input type="text" name="phone_number" value="{{ user.phone_number }}">
                </td>
                <th>年龄</th>
                <td>
                    <input type="text" name="age" value="{{ user.age }}">
                </td>
            </tr>
            <tr>
                <th>性别</th>
                <td>
                    <select name="gender" id="" >
                        <option value="0">女</option>
                        <option value="1">男</option>
                        <option value="{{ user.gender }}" selected hidden>{{ user.get_gender_display }}</option>
                    </select>
                </td>
                <th>地址</th>
                <td>
                    <input type="text" name="address" value="{{ user.address }}">
                </td>
            </tr>
            <tr>

                <td colspan="5" style="text-align:center">
                    <input type="submit" class="btn btn-primary" value="完善个人信息">
                </td>
            </tr>
        </table>
    </form>
{% endblock %}

DjangoLogin/templates/vuedemo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="/static/js/vue.min.js"></script>
</head>
<body>
{% verbatim %}
<div id="content">
    helloworld{{ name }}{{ age }}
</div>
{% endverbatim %}
<script>
    var vue =new Vue(
        {
            el:'#content',
            data:{
                name:'yan',
                age:22
            }
        }
    )
</script>
</body>
</html>