Qshop/Buyer/urls.py
from django.urls import path,re_path
from .views import *
from django.views.decorators.cache import cache_page

urlpatterns = [
    path('index/',cache_page(200)(index)),
    path('login/',login),
    path('logout/',logout),
    path('register/',register),
    path('base/',base),
    path('goodslist/',goodslist),
    re_path('detail/(?P<goods_id>\d+)/',detail),
    path('user_center_info/',user_center_info),
    path('cart/',cart),
    path('place_order/',place_order),
    path('alipayorder/',alipayorder),
    path('payresult/',payresult),
    path('add_cart/',add_cart),
    path('del_cart/',del_cart),
    path('place_order_more/',place_order_more),
    path('user_center_order/',user_center_order),
    path('user_center_site/',user_center_site),
    path('test/',test),
]

Qshop/Qshop/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from Buyer.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('seller/',include('Seller.urls')),
    path('buyer/',include('Buyer.urls')),
    re_path('^$',index),
]

Qshop/Buyer/models.py
from django.db import models
from Seller.models import LoginUser,Goods

# Create your models here.
ORDER_STATUS = (
        (1,'未支付'),
        (2,'已支付'),
        (3,'待发货'),
        (4,'已发货'),
        (5,'完成'),
        (6,'拒收')
        )

class PayOrder(models.Model):
    order_number =models.CharField(max_length=32,verbose_name="订单编号")
    order_date =models.DateField(auto_now=True,verbose_name="创建日期")
    order_status =models.IntegerField(choices=ORDER_STATUS,verbose_name="订单状态")
    order_total = models.FloatField(verbose_name="订单总价")
    order_user =models.ForeignKey(to=LoginUser,on_delete=models.CASCADE)
    class Meta:
        db_table = 'payorder'
        verbose_name = '订单表'


class OrderInfo(models.Model):
    order_id =models.ForeignKey(to=PayOrder,on_delete=models.CASCADE)
    goods =models.ForeignKey(to=Goods,on_delete=models.CASCADE)
    goods_price = models.FloatField(verbose_name="商品单价") ## 订单创建的时候商品单价
    goods_count = models.IntegerField(verbose_name="订单商品数量")
    goods_total_price = models.FloatField(verbose_name="商品小计")
    class Meta:
        db_table = 'orderinfo'
        verbose_name = "订单详情表"


class Cart(models.Model):
    goods = models.ForeignKey(to=Goods,on_delete=models.CASCADE,verbose_name="商品表外键")
    goods_number = models.IntegerField(verbose_name="商品数量")
    cart_user = models.ForeignKey(to=LoginUser,on_delete=models.CASCADE,verbose_name="买家")
    goods_total = models.FloatField(verbose_name="单件商品的总价")
    payorder = models.CharField(default='1',verbose_name='订单表的订单号',max_length=32)
    class Meta:
        db_table = "cart"
        verbose_name = "购物车表"

Qshop/Buyer/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect,JsonResponse
from Seller.views import setPassword
from Seller.models import *
from .models import *
from django.db.models import Q

# Create your views here.

def LoginValid(func):
    def inner(request,*args,**kwargs):
        email=request.COOKIES.get('email')
        email_session=request.session.get('email')
        cookie_username=request.COOKIES.get('username')
        if email and email_session and email==email_session:
            flag=LoginUser.objects.filter(username=cookie_username,email=email,user_type=1).exists()
            if flag:
                return func(request,*args,**kwargs)
            else:
                return HttpResponseRedirect('/buyer/login')
        else:
            return HttpResponseRedirect('/buyer/login/')
    return inner

from django.views.decorators.cache import cache_page

# @LoginValid
cache_page(120)
def index(request):
    types=[]
    goods_type=GoodsType.objects.all()
    for one in goods_type:
        goods=one.goods_set.order_by('goods_price')
        if len(goods)>4:
            goods_all=goods[:4]
            types.append({'type':one,'goods':goods_all})
        elif len(goods)>0 and len(goods)<=4:
            goods_all=goods
            types.append({'type':one,'goods':goods_all})
    return render(request,'buyer/index.html',locals())

def login(request):
    email = request.POST.get('username')
    password = request.POST.get('pwd')
    if email and password:
        flag = LoginUser.objects.filter(email=email, password=setPassword(password),user_type=1).first()
        if flag:
            response = HttpResponseRedirect('/buyer/index')
            response.set_cookie('email', email)
            response.set_cookie('username', flag.username)
            response.set_cookie('user_id', flag.id)
            request.session['email'] = email
            return response
        else:
            result = '账号或密码错误'
    else:
        result = '账号密码不能为空'
    return render(request, 'buyer/login.html', locals())

def register(request):
    email = request.POST.get('email')
    password = request.POST.get('pwd')
    repassword = request.POST.get('cpwd')
    if email and password and repassword:
        if password != repassword:
            result = '密码不一致'
        else:
            flag = LoginUser.objects.filter(email=email).exists()
            if flag:
                result = '用户已存在'
            else:
                LoginUser.objects.create(email=email, username=email, password=setPassword(password),user_type=0)
                result = '注册成功'
    else:
        result = '账号密码不能为空'
    return render(request, 'buyer/register.html', locals())


def logout(request):
    response = HttpResponseRedirect('/buyer/login')
    response.delete_cookie('email')
    response.delete_cookie('username')
    response.delete_cookie('user_id')
    del request.session['email']
    return response


def base(request):

    return render(request,'buyer/base.html')

def goodslist(request):

    req_type = request.GET.get("req_type")
    keywords = request.GET.get("keywords")
     ## 查看指定类型的的商品
    if req_type == 'findall':
        goods_type = GoodsType.objects.get(id =int(keywords))
        goods_all = goods_type.goods_set.all()
        print(goods_all)
    ## 搜索 进行模糊查询
    else:
        goods_all =Goods.objects.filter(goods_name__icontains=keywords).all()
    ## 从搜索进来
    ## 进行模糊查询

    goods_new = goods_all.order_by("-goods_pro_time")[:2]
    return render(request,"buyer/goodslist.html",locals())

def detail(request,goods_id):
    goods=Goods.objects.get(id=int(goods_id))
    return render(request,'buyer/detail.html',locals())


def user_center_info(request):
    username=request.COOKIES.get('email')
    user=LoginUser.objects.filter(email=username).first()
    return render(request,'buyer/user_center_info.html',locals())

@LoginValid
def cart(request):

    user_id = request.COOKIES.get("user_id")
    order_number=PayOrder.objects.filter(order_user=LoginUser.objects.get(id=user_id),order_status=1).values('order_number')
    print(order_number)

    ## 查找用户的购物车内容， 按照时间逆序


    cart1=Cart.objects.filter(Q(payorder__in=order_number)|Q(payorder='1')).all().order_by('-id')

    return render(request,'buyer/cart.html',locals())

def user_center_order(request):
    user_id=request.COOKIES.get('user_id')
    payorder=PayOrder.objects.filter(order_user=LoginUser.objects.get(id=user_id)).all().order_by('order_status')
    return render(request,'buyer/user_center_order.html',locals())


def user_center_site(request):
    email=request.COOKIES.get('email')
    user=LoginUser.objects.filter(email=email).first()
    return render(request,'buyer/user_center_site.html',locals())

import time
def place_order(request):
    user_id=request.COOKIES.get('user_id')
    goods_id=request.GET.get('goods_id')
    goods_count=request.GET.get('goods_count')
    goods=Goods.objects.get(id=int(goods_id))
    payorder=PayOrder()
    payorder.order_number=str(time.time()).replace('.','')
    payorder.order_status='1'
    payorder.order_total=goods.goods_price * int(goods_count)
    payorder.order_user=LoginUser.objects.get(id=int(user_id))
    payorder.save()

    orderinfo = OrderInfo()
    orderinfo.order_id = payorder
    orderinfo.goods = goods
    orderinfo.goods_price = goods.goods_price
    orderinfo.goods_count = int(goods_count)
    orderinfo.goods_total_price = goods.goods_price * int(goods_count)
    orderinfo.save()
    return render(request,'buyer/place_order.html',locals())

from Qshop.settings import alipay

def alipayorder(request):
    order_id=request.GET.get('order_id')
    payorder = PayOrder.objects.get(id=order_id)
    order_string = alipay.api_alipay_trade_page_pay(
        subject='生鲜交易',  ## 交易主题
        out_trade_no=payorder.order_number,  ## 订单号
        total_amount=str(payorder.order_total),  ## 交易总金额  需要是一个string
        return_url='http://127.0.0.1:8000/buyer/payresult/',  ## 返回的路径
        notify_url=None
    )
    result = "https://openapi.alipaydev.com/gateway.do?" + order_string
    return HttpResponseRedirect(result)



def payresult(request):
    out_trade_no=request.GET.get('out_trade_no')
    payorder=PayOrder.objects.get(order_number=out_trade_no)
    payorder.order_status=2
    payorder.save()
    return render(request,'buyer/payresult.html',locals())



def add_cart(request):
    goods_id=request.POST.get('goods_id')
    count=request.POST.get('count',1)
    user_id=request.COOKIES.get('user_id')
    goods=Goods.objects.get(id=goods_id)
    user=LoginUser.objects.get(id=user_id)
    has_cart=Cart.objects.filter(goods=goods,cart_user=user,payorder='1').first()
    if has_cart:
        has_cart.goods_number+= int(count)
        has_cart.goods_tatal+=int(count)*goods.goods_price
        has_cart.save()
    else:
        cart=Cart()
        cart.goods=goods
        cart.goods_number=int(count)
        cart.cart_user=LoginUser.objects.get(id=user_id)
        cart.goods_total=int(count) * goods.goods_price
        cart.save()

    return JsonResponse({'code':10000,'msg':'添加购物成功'})



def place_order_more(request):
    user_id=request.COOKIES.get('user_id')
    data=request.POST
    data=data.items()
    res=[]
    for k,v in data:
        if k.startswith('cartid'):
            res.append(v)
    user=LoginUser.objects.get(id=user_id)
    print(res)
    if len(res)!=0:
        payorder = PayOrder()
        payorder.order_number =str(time.time()).replace(".", "")
        payorder.order_status = 1  ## 未支付
        payorder.order_total = 0
        payorder.order_user = user
        payorder.save()

        order_total = 0
        order_count = 0
        for c_id in res:  ## c_id 购物车id
            cart = Cart.objects.get(id=c_id)
            goods = cart.goods
            orderinfo = OrderInfo()
            orderinfo.order_id = payorder
            orderinfo.goods = goods
            orderinfo.goods_price = goods.goods_price
            orderinfo.goods_count = cart.goods_number
            orderinfo.goods_total_price = cart.goods_total
            orderinfo.save()
            order_total += cart.goods_total
            order_count += cart.goods_number

            cart.payorder=payorder.order_number
            cart.save()
        payorder.order_total = order_total
        payorder.save()
    return render(request,'buyer/place_order.html',locals())




def del_cart(request):
    cart_id=request.GET.get('cart_id')
    Cart.objects.filter(id=cart_id).delete()
    return HttpResponseRedirect('/buyer/cart')


def test(request):

    return render(request,'buyer/test.html')

Qshop/Buyer/templates/buyer/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>{% block title %}{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="/static/buyer/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/buyer/css/main.css">
	<script type="text/javascript" src="/static/buyer/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript" src="/static/buyer/js/jquery-ui.min.js"></script>
	<script type="text/javascript" src="/static/buyer/js/slide.js"></script>
    {% block style %}
    
    {% endblock %}
</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				<div class="login_info fl">
					欢迎您：<em>张 山</em>
				</div>
				<div class="login_btn fl">
                    {% if request.COOKIES.username %}
                        <a href="#">{{ request.COOKIES.username }}</a>
                        <span>|</span>
                        <a href="/buyer/logout">退出</a>
                    {% else %}
                        <a href="/buyer/login">登录</a>
                        <span>|</span>
                        <a href="/buyer/register">注册</a>
                    {% endif %}
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="/buyer/user_center_info">用户中心</a>
					<span>|</span>
					<a href="/buyer/cart">我的购物车</a>
					<span>|</span>
					<a href="/buyer/user_center_order">我的订单</a>
				</div>
			</div>
		</div>
	</div>

	<div class="search_bar clearfix">
		<a href="/buyer/index" class="logo fl"><img src="/static/buyer/images/logo.png"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" id="keywords" name="" placeholder="搜索商品">
			<input type="button" onclick="getgoods()" class="input_btn fr" name="" value="搜索">
		</div>
		<div class="guest_cart fr">
			<a href="/buyer/cart" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">1</div>
		</div>
	</div>
    {% block content %}

    {% endblock %}


	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	<script type="text/javascript" src="/static/buyer/js/slideshow.js"></script>
	<script type="text/javascript">
		{#BCSlideshow('focuspic');#}
		{#var oFruit = document.getElementById('fruit_more');#}
		var oShownum = document.getElementById('show_count');

		var hasorder = localStorage.getItem('order_finish');

		if(hasorder)
		{
			oShownum.innerHTML = '2';
		}

		{#oFruit.onclick = function(){#}
		{#	window.location.href = 'list.html';#}



	</script>
    <script>
        function getgoods() {
            var keywords=$('#keywords').val();
            url= 'http://127.0.0.1:8000/buyer/goodslist/?req_type=search&keywords=' + keywords;
            console.log(url);
            window.location.href = url;
            console.log(11111)
        }
    </script>
    {% block script %}
    
    {% endblock %}
</body>
</html>

Qshop/Buyer/templates/buyer/cart.html
{% extends 'buyer/base.html' %}
{% block title %}
购物车
{% endblock %}
{% block content %}
	<div class="total_count">全部商品<em>2</em>件</div>
	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>
    <form action="/buyer/place_order_more/" method="post">
    {% csrf_token %}
    {% for one in cart1 %}
    <ul class="cart_list_td clearfix">
		<li class="col01"><input type="checkbox" name="cartid{{ one.id }}" class="goods_box" value="{{ one.id }}"></li>
		<li class="col02"><img src="/static/{{ one.goods.goods_picture }}"></li>
		<li class="col03">{{ one.goods.goods_name }}<br><em>{{ one.goods.goods_price }}元/500g</em></li>
		<li class="col04">500g</li>
		<li class="col05">{{ one.goods.goods_price }}元</li>
		<li class="col06">
			<div class="num_add">
				<a href="javascript:;" class="add fl">+</a>
				<input type="text" class="num_show fl" value="{{ one.goods_number }}">
				<a href="javascript:;" class="minus fl">-</a>
			</div>
		</li>
		<li class="col07">{{ one.goods_total }}元</li>
		<li class="col08"><a href="/buyer/del_cart/?cart_id={{ one.id }}" id="del">删除</a></li>
	</ul>
    {% endfor %}


	<ul class="settlements">
		<li class="col01"><input type="checkbox" name="" id="all_box"></li>
		<li class="col02">全选</li>
		<li class="col03">合计(不含运费)：<span>¥</span><em id="total_mount">0</em><br>共计<b id="number">0</b>件商品</li>
		<li class="col04"><input type="submit" value="去结算" ></li>
	</ul>
    </form>
{% endblock %}

{% block script %}
    <script>
        $('#all_box').click(function () {
            if (this.checked){
                $('.goods_box').prop('checked',true);
            } else {
                $('.goods_box').prop('checked',false);
            }
            add()
        });

        $('.goods_box').each(
            function () {
                $(this).click(function () {
                    if (!this.checked){
                        $('#all_box').prop('checked',false)
                    }
                    add()
                })
            }
        );

    
    function add() {
        var dict={'num':0,'total_mount':0};
        $('.goods_box').each(
            function () {
                if(this.checked){
                    //var number=parseInt($(this).parent('.cart_list_td').find('.num_show').val());
                    var total = parseFloat($(this).parents(".cart_list_td").find(".col07").text());
                    dict.num +=1;
                    dict.total_mount+=total;
                }
            }
        );

        $('#number').text(dict.num);
        $('#total_mount').text(dict.total_mount)
    }
    

    </script>
{% endblock %}

Qshop/Buyer/templates/buyer/detail.html
{% extends 'buyer/base.html' %}
{% block title %}
商品详情页
{% endblock %}
{% block content %}
	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">新鲜水果</a>
		<span>></span>
		<a href="#">商品详情</a>
	</div>

	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl"><img style="height: 100%;width: 100%" src="/static/{{ goods.goods_picture }}"></div>

		<div class="goods_detail_list fr">
			<h3>{{ goods.goods_name }}</h3>
			<div class="prize_bar">
				<span class="show_pirze">¥<em id="price">{{ goods.goods_price }}</em></span>
				<span class="show_unit">单  位：500g</span>
			</div>
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：{{ goods.goods_count }}</div>
				<div class="num_add fl">
					<input type="text" class="num_show fl" id="num" value="1">
					<a id="add" href="javascript:;" class="add fr">+</a>
					<a id="minus" href="javascript:;" class="minus fr">-</a>
				</div>
			</div>
			<div class="total">总价：<em id="total">{{ goods.goods_price }}</em>元</div>
			<div class="operate_btn">
				<a href="javascript:;" class="buy_btn" id="buynow">立即购买</a>
				<a href="javascript:;" class="add_cart" id="add_cart" onclick="add_cart()">加入购物车</a>
			</div>
		</div>
	</div>

    <div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
{#			<div class="new_goods">#}
{#				<h3>新品推荐</h3>#}
{#				<ul>#}
{#					<li>#}
{#						<a href="#"><img src="images/goods/goods001.jpg"></a>#}
{#						<h4><a href="#">进口柠檬</a></h4>#}
{#						<div class="prize">￥3.90</div>#}
{#					</li>#}
{#					<li>#}
{#						<a href="#"><img src="images/goods/goods002.jpg"></a>#}
{#						<h4><a href="#">玫瑰香葡萄</a></h4>#}
{#						<div class="prize">￥16.80</div>#}
{#					</li>#}
{#				</ul>#}
{#			</div>#}
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active">商品介绍</li>
				<li>评论</li>
			</ul>

			<div class="tab_content">
				<dl>
					<dt>商品详情：</dt>
					<dd>{{ goods.goods_description }} </dd>
				</dl>
			</div>

		</div>
	</div>

{% endblock %}
{% block script %}
    <script>
    $('#add').click(function () {
        var number=parseInt($('#num').val());
        number=number+1;
        price=parseFloat($('#price').text());
        total_mount=(price * number).toFixed(2);
        $('#num').val(number);
        $('#total').text(total_mount);
    });

    $('#minus').click(function () {
        var number=parseInt($('#num').val());
        number=number-1;
        if (number<=1){
            number=1
        }
        price=parseFloat($('#price').text());
        total_mount=(price * number).toFixed(2);
         $('#num').val(number);
        $('#total').text(total_mount);
    });

    $('#buynow').click(function () {
        var goods_count= $('#num').val();
        var goods_id ={{ goods_id }};
        url='http://127.0.0.1:8000/buyer/place_order/?goods_count='+goods_count+'&goods_id='+goods_id;
        window.location.href=url;
    });




        function add_cart(){
            console.log(111111111);
            var goods_id = {{ goods.id }};
            count=$('#num').val();
            // ajax
            // 构建请求参数
            send_data = {
                "goods_id":goods_id,
                'count':count,
                "csrfmiddlewaretoken":"{{ csrf_token }}"
            };
            $.ajax({
                url:"/buyer/add_cart/",
                type:'post',
                data:send_data,
                success:function (data) {
                    console.log(data);
                    alert(data.msg)
                },
                error:function (error) {
                    console.log(error)
                }

            })

        }



    </script>

{% endblock %}

Qshop/Buyer/templates/buyer/payresult.html
{% extends 'buyer/base.html' %}
{% block title %}
支付结果
{% endblock %}
{% block content %}
<div class="list_moder">
<h1>支付结果</h1>
<table>
    {% for key,value in request.GET.items  %}
        <tr>
        <th>{{ key }}</th>
        <td>{{ value }}</td>
        </tr>

    {% endfor %}

</table>
</div>
{% endblock %}

Qshop/Buyer/templates/buyer/place_order.html
{% extends 'buyer/base.html' %}

{% block title %}
提交订单
{% endblock %}
{% block content %}
    <h3 class="common_title">确认收货地址</h3>

	<div class="common_list_con clearfix">
		<dl>
			<dt>寄送到：</dt>
			<dd><input type="radio" name="" checked="">北京市 海淀区 东北旺西路8号中关村软件园 （李思 收） 182****7528</dd>
		</dl>
		<a href="user_center_site.html" class="edit_site">编辑收货地址</a>

	</div>

	<h3 class="common_title">支付方式</h3>
	<div class="common_list_con clearfix">
		<div class="pay_style_con clearfix">
			<input type="radio" name="pay_style">
			<label class="cash">货到付款</label>
			<input type="radio" name="pay_style">
			<label class="weixin">微信支付</label>
			<input type="radio" name="pay_style" checked>
			<label class="zhifubao"></label>
			<input type="radio" name="pay_style">
			<label class="bank">银行卡支付</label>
		</div>
	</div>

	<h3 class="common_title">商品列表</h3>

	<div class="common_list_con clearfix">
		<ul class="goods_list_th clearfix">
			<li class="col01">商品名称</li>
			<li class="col02">商品单位</li>
			<li class="col03">商品价格</li>
			<li class="col04">数量</li>
			<li class="col05">小计</li>
		</ul>
        {% for one in payorder.orderinfo_set.all %}


		<ul class="goods_list_td clearfix">
			<li class="col01">·</li>
			<li class="col02"><img src="/static/{{ one.goods.goods_picture }}"></li>
			<li class="col03">{{ one.goods.goods_name }}</li>
			<li class="col04">500g</li>
			<li class="col05">{{ one.goods_price }}</li>
			<li class="col06">{{ one.goods_count }}</li>
			<li class="col07">{{ one.goods_total_price }}元</li>
		</ul>

    {% endfor %}
	</div>

	<h3 class="common_title">总金额结算</h3>

	<div class="common_list_con clearfix">
		<div class="settle_con">
			<div class="total_goods_count">共<em>{{ orderinfo.goods_count }}</em>件商品，总金额<b>{{ orderinfo.goods_total_price }}</b></div>
			<div class="transit">运费：<b>0元</b></div>
			<div class="total_pay">实付款：<b>{{ orderinfo.goods_total_price }}</b></div>
		</div>
	</div>

	<div class="order_submit clearfix">
		<a href="/buyer/alipayorder/?order_id={{ payorder.id }}" id="order_btn">提交订单</a>
	</div>
{% endblock %}

Qshop/Buyer/templates/buyer/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{% load myfilter %}

{{ 30 | myadd }}

{{ 12 | mymangadd:13 }}

{% myalladd 1 2 3 4 %}

</body>
</html>

Qshop/Buyer/templates/buyer/user_center_order.html
{% extends 'buyer/base.html' %}
{% block title %}
我的订单
{% endblock %}
{% block content %}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/buyer/user_center_info">· 个人信息</a></li>
				<li><a href="/buyer/user_center_order" class="active">· 全部订单</a></li>
				<li><a href="/buyer/user_center_site">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
            {% for one in payorder %}
            <ul class="order_list_th w978 clearfix">
					<li class="col01">{{ one.order_date }}</li>
					<li class="col02">订单号：{{ one.order_number }}</li>
					<li class="col02 stress">{{ one.get_order_status_display }}</li>
				</ul>

				<table class="order_list_table w980">

							<td width="55%">
                                {% for one in one.orderinfo_set.all %}
                                <ul class="order_goods_list clearfix">
									<li class="col01"><img src="/static/{{ one.goods.goods_picture }}"></li>
									<li class="col02">{{ one.goods.goods_name }}<em>{{ one.goods_price }}元/500g</em></li>
									<li class="col03">{{ one.goods_count }}</li>
									<li class="col04">{{ one.goods_total_price }}元</li>
								</ul>
                                {% endfor %}
							</td>
							<td width="15%">{{ one.order_total }}元</td>
                        {% if one.order_status == 1 %}
                        <td width="15%">待付款</td>
							<td width="15%"><a href="/buyer/alipayorder/?order_id={{ one.id }}" class="oper_btn">去付款</a></td>
                        {% else %}
                        <td width="15%">已付款</td>
							<td width="15%"><a href="#" class="oper_btn">产看物流</a></td>
                        {% endif %}


				</table>
            {% endfor %}




				<div class="pagenation">
					<a href="#">上一页</a>
					<a href="#" class="active">1</a>
					<a href="#">2</a>
					<a href="#">3</a>
					<a href="#">4</a>
					<a href="#">5</a>
					<a href="#">下一页></a>
				</div>
		</div>
	</div>
{% endblock %}